drop database if exists bdEscola;
create database bdEscola;
use bdEscola;

CREATE TABLE ALUNO (
RA			INT				NOT NULL,
NOME		VARCHAR(50) 	NOT NULL,
CPF			VARCHAR(11)		NOT NULL,
CEP			VARCHAR(8)		NULL,
LOGRADOURO 	VARCHAR(40)		NULL,
NUMERO		VARCHAR(8)		NULL,
COMPLEMENTO VARCHAR(30) 	NULL,
CIDADE		VARCHAR(40)		NULL,
BAIRRO		VARCHAR(40)		NULL,
UF			VARCHAR(2)		NULL,
TELEFONE 	INT				NULL,
GENERO		INT				NOT NULL,
RENDA 		DOUBLE(8,2) 	null,
PRIMARY KEY (RA)
);
